#
# File: \config\packages\psw_expiration.yaml
# Author: Peter Nagy <peter@antronin.consulting>
# -----
psw_expiration:
    lifetime: '%env(int:PASSWORD_LIFETIME)%'
    warning_threshold: '%env(int:PASSWORD_WARNING_THRESHOLD)%'
    unit: '%env(PASSWORD_EXPIRATION_UNIT)%'
